# Generated by Django 3.0.7 on 2020-07-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_div',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
    ]
